### ISSUE TITLE
latest software version cannot be found here

### ISSUE THREAD

**Issue by jonnybitcoin** [bitshares/bitshares.github.io-old#68]
The latest official release can always be found on GitHub at this URL: https://github.com/bitshares/bitshares-2/releases/latest

**Comment by xeroc** [comment]
That url is already linked in https://bitshares.org/download/

**Comment by jonnybitcoin** [comment]
Yes but it doesn't link to the latest version

**Comment by xeroc** [comment]
ah .. you mean the direct download links to the raw files ..

fixed:
https://github.com/bitshares/bitshares.github.io/commit/ccc78b77d709ed29cd47fcb6bc5aa0b4119306f1

**Comment by jonnybitcoin** [comment]
Still doesn't link to the latest version. It links to this old version
BitShares GUI 2.0.151119

**Comment by xeroc** [comment]
Ah .. I see ... That's @valzav missing something for github when publishing a release ..

AFAIK, a new release is scheduled for today .. I would simply wait for it and fix it then :)

**Comment by valzav** [comment]
Strange, I've updated the links a week ago: https://github.com/bitshares/bitshares.github.io/commit/f50119485d47996fc1e90915181045086cf2b076

**Comment by xeroc** [comment]
May have been my fault .. Sorry about that
I am closing this issue for now as the link is now correct .. (at least for a week :) )
